### ISSUE TITLE
type error in readme

### ISSUE THREAD

**Issue by peterrobertz** [superReal/srunit#7]
\SrUnit\Boostrap::create(__DIR__)->bootstrap(); is wrong

\SrUnit\Boostrap::create(__DIR__)->bootstrap(); is right

BOOTSTRAP instead BOOSTRAP, 5 living hours head meets wall :)

**Comment by jenswiese** [comment]
Hey Peter, sorry for your headache. I fixed it right away f9f4634066e3480fc4bbc073459e9ff733fa0402

**Comment by peterrobertz** [comment]
woah, that was fast, thank you <3
