### ISSUE TITLE
Which oxid version

### ISSUE THREAD

**Issue by peterrobertz** [superReal/srunit#8]
Hm, i don't get it running properly.

My oxid version is 4.9.2 CE, is it right to use this version?

i've created a test module, which implement a class (assigns in metadata.php under "files"), extends from oxbase and implements a "foo" function.

if i create a mock from this class, in my test files, i just get a "...::foo() does not exists on this mock object".

maybe im totally stupid, but has anyone an idea?

**Comment by jenswiese** [comment]
Hey Peter,

first of all: this library is not intended to work only with a particular version, it all depends on what you're actually want to do/test?

Could you share the code with me (maybe just point me to your project)? It would be much easier to figure out your problem?

Cheers Jens.

**Comment by jenswiese** [comment]
Hey @peterrobertz,

do you have any news on that?

Jens.

**Comment by peterrobertz** [comment]
Hey sorry for my non-response

i now use the original oxid tests, works great for me.

mein englisch ist nicht das beste, ich benutze die originalen oxid tests und packe meine eigenen test-szenarien in die vorhandene verzeichnis-struktur. mit gulp/nodejs habe ich einen watch programmiert, immer dann, wenn ich meinen quellcode verändere, werden die passenden (nicht die gesamten) tests ausgeführt.

ich hatte noch ein bisschen versucht srunit zu implementieren, aber im endeffekt ist mir nicht ganz klar, wofür ich srunit als weiteren "wrapper" (?) ontop brauche

flutscht wie sau :)

**Comment by jenswiese** [comment]
"Flutsch wie Sau" ist natürlich immer besser. :)

Danke, Jens.
